stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py
    deps:
    - .\data\ingested\student_performance.csv
    - .\src\data\make_dataset.py
    params:
    - make_dataset.random_state
    - make_dataset.test_size
    outs:
    - .\data\raw\
