stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py
    deps:
    - .\data\ingested\student_performance.csv
    - .\src\data\make_dataset.py
    params:
    - make_dataset.random_state
    - make_dataset.test_size
    outs:
    - .\data\raw\
    
  build_features:
    cmd: python .\src\features\build_features.py
    deps:
    - .\data\raw\
    - .\src\features\build_features.py
    params:
    - build_features.n_components
    outs:
    - .\data\processed\
    - .\models\preprocessor.joblib
